-- BotForge: server-side persistence for bots, keys, transcripts and agent action items.
--
-- SECURITY MODEL
-- There is no Supabase Auth in this app. RLS is therefore not an authorization
-- mechanism here -- it is a blast shield. Every table below has RLS enabled with
-- ZERO policies, so an anon/publishable key can read nothing. All access goes
-- through the serverless functions in /api using SUPABASE_SERVICE_ROLE_KEY,
-- which bypasses RLS. Authorization is the admin-token check in those handlers.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- lead_captures -- PRE-EXISTING table used by the legacy DesignInc concierge
-- (api/lead-capture.ts writes it, api/leads.ts reads it). Declared idempotently
-- so a fresh project gets it too; "if not exists" leaves the live table alone.
-- id is an integer because src/pages/LeadsDashboard.tsx types it as number.
-- ---------------------------------------------------------------------------
create table if not exists public.lead_captures (
  id           bigint generated by default as identity primary key,
  ai           text,
  ai_name      text,
  email        text,
  summary      text,
  captured_at  timestamptz,
  created_at   timestamptz not null default now(),
  source       text
);

-- matches the order clause in api/leads.ts
create index if not exists lead_captures_captured_idx
  on public.lead_captures (captured_at desc nulls last);
-- matches the optional ?ai= ilike filter in api/leads.ts
create index if not exists lead_captures_ai_idx on public.lead_captures (ai);

-- ---------------------------------------------------------------------------
-- bots -- replaces the localStorage key botforge:bots:v1
--
-- id is TEXT, not uuid, deliberately: it keeps the nanoid(10) ids already in
-- users' localStorage, so migration is a straight copy with no id remapping and
-- existing /chatterbox/bots/:id/edit bookmarks keep working.
-- ---------------------------------------------------------------------------
create table if not exists public.bots (
  id                 text primary key,
  slug               text not null unique,
  name               text not null default 'Untitled Bot',
  bio                text not null default '',
  description        text not null default '',
  avatar_url         text,
  avatar_initials    text not null default 'B',
  theme_color        text not null default '#0ea5e9',

  system_prompt      text not null default '',
  greeting           text not null default '',
  starter_prompts    jsonb not null default '[]'::jsonb,

  provider_id        text not null default 'anthropic',
  model_id           text not null default 'claude-sonnet-5',
  temperature        real not null default 0.7,
  max_tokens         integer not null default 1024,
  top_p              real not null default 1,
  memory             text not null default 'session',

  chat_theme         text not null default 'default',

  visibility         text not null default 'unlisted',
  status             text not null default 'DRAFT',
  content_filter     text not null default 'moderate',
  tags               jsonb not null default '[]'::jsonb,
  language           text not null default 'en',
  allowed_domains    jsonb not null default '[]'::jsonb,

  -- "Act as an Agent" settings
  agent_enabled      boolean not null default false,
  agent_actions      jsonb not null default '[]'::jsonb,

  -- Abuse cap. /api/bot-chat is a public endpoint that spends the owner's money,
  -- so this exists from day one rather than being retrofitted after a bill.
  daily_message_cap  integer not null default 500,

  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  published_at       timestamptz,

  constraint bots_status_chk     check (status in ('DRAFT','PUBLISHED','UNPUBLISHED','ARCHIVED')),
  constraint bots_visibility_chk check (visibility in ('public','unlisted','private')),
  constraint bots_memory_chk     check (memory in ('none','session','persistent'))
);

create index if not exists bots_status_updated_idx on public.bots (status, updated_at desc);

-- ---------------------------------------------------------------------------
-- knowledge_docs -- its own table rather than jsonb on bots.
-- Knowledge content is capped at 200k chars per doc (lib/knowledge.ts), and the
-- editor autosaves on an 800ms debounce. Kept inline, every keystroke burst
-- would POST megabytes. Knowledge is saved eagerly on add/remove instead.
-- ---------------------------------------------------------------------------
create table if not exists public.knowledge_docs (
  id          text primary key,
  bot_id      text not null references public.bots (id) on delete cascade,
  file_name   text not null,
  mime_type   text not null default 'text/plain',
  char_count  integer not null default 0,
  content     text not null default '',
  added_at    timestamptz not null default now()
);

create index if not exists knowledge_docs_bot_idx on public.knowledge_docs (bot_id, added_at);

-- ---------------------------------------------------------------------------
-- provider_keys -- replaces the localStorage key botforge:apikeys:v1.
-- Stored so the browser never holds a provider credential. The API returns only
-- key_hint to the client; api_key itself is never sent over the wire.
-- ---------------------------------------------------------------------------
create table if not exists public.provider_keys (
  provider_id  text primary key,
  api_key      text not null,
  key_hint     text not null default '',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- chat_sessions / chat_messages -- conversations were previously never stored.
-- visitor_ip_hash is sha256(ip || VISITOR_IP_SALT): enough to rate-limit a
-- visitor without storing their IP.
-- ---------------------------------------------------------------------------
create table if not exists public.chat_sessions (
  id               uuid primary key default gen_random_uuid(),
  bot_id           text not null references public.bots (id) on delete cascade,
  started_at       timestamptz not null default now(),
  last_message_at  timestamptz not null default now(),
  message_count    integer not null default 0,
  visitor_ip_hash  text,
  user_agent       text,
  referrer         text,
  origin           text,
  analyzed_at      timestamptz,
  ended_at         timestamptz
);

create index if not exists chat_sessions_bot_idx
  on public.chat_sessions (bot_id, last_message_at desc);
create index if not exists chat_sessions_ip_idx
  on public.chat_sessions (visitor_ip_hash, started_at desc);
-- watermark for the sweeper that catches visitors who closed the tab mid-stream
create index if not exists chat_sessions_unanalyzed_idx
  on public.chat_sessions (last_message_at) where analyzed_at is null;

create table if not exists public.chat_messages (
  id                 bigint generated by default as identity primary key,
  session_id         uuid not null references public.chat_sessions (id) on delete cascade,
  bot_id             text not null references public.bots (id) on delete cascade,
  role               text not null check (role in ('user','assistant','system')),
  content            text not null default '',
  -- cheap regex pass result, e.g. {"email":true,"phone":false,"booking":true}
  signals            jsonb,
  prompt_tokens      integer,
  completion_tokens  integer,
  provider_id        text,
  model_id           text,
  latency_ms         integer,
  created_at         timestamptz not null default now()
);

create index if not exists chat_messages_session_idx
  on public.chat_messages (session_id, created_at);
create index if not exists chat_messages_bot_time_idx
  on public.chat_messages (bot_id, created_at desc);

-- ---------------------------------------------------------------------------
-- leads -- Lead Magnet action. Bot-scoped; distinct from the legacy
-- lead_captures table, which keeps serving the DesignInc concierge.
-- context_snippet is the "small info from the chat for context" the Action
-- Items page shows: the last user turn plus the preceding assistant turn.
-- ---------------------------------------------------------------------------
create table if not exists public.leads (
  id               bigint generated by default as identity primary key,
  bot_id           text   references public.bots (id)          on delete set null,
  session_id       uuid   references public.chat_sessions (id) on delete set null,
  message_id       bigint references public.chat_messages (id) on delete set null,
  name             text,
  email            text,
  phone            text,
  company          text,
  intent           text,
  summary          text,
  context_snippet  text not null default '',
  confidence       real,
  detected_by      text not null default 'regex',
  status           text not null default 'NEW',
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint leads_status_chk check (status in ('NEW','CONTACTED','DONE','SPAM'))
);

create index if not exists leads_status_time_idx on public.leads (status, created_at desc);
create index if not exists leads_bot_idx         on public.leads (bot_id, created_at desc);
-- one lead per (session, email): re-typing an address mid-chat is not a new lead
create unique index if not exists leads_session_email_idx
  on public.leads (session_id, lower(email))
  where session_id is not null and email is not null;

-- ---------------------------------------------------------------------------
-- meeting_requests -- Scheduler action.
-- requested_for holds a resolved timestamp when one could be derived;
-- requested_for_text always holds the visitor's own words ("next Tuesday pm").
-- ---------------------------------------------------------------------------
create table if not exists public.meeting_requests (
  id                  bigint generated by default as identity primary key,
  bot_id              text   references public.bots (id)          on delete set null,
  session_id          uuid   references public.chat_sessions (id) on delete set null,
  lead_id             bigint references public.leads (id)         on delete set null,
  name                text,
  email               text,
  requested_for       timestamptz,
  requested_for_text  text,
  timezone            text,
  duration_minutes    integer,
  topic               text,
  context_snippet     text not null default '',
  confidence          real,
  status              text not null default 'NEW',
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  constraint meeting_status_chk check (status in ('NEW','SCHEDULED','DECLINED','DONE'))
);

create index if not exists meeting_requests_status_idx
  on public.meeting_requests (status, created_at desc);
create index if not exists meeting_requests_lead_idx on public.meeting_requests (lead_id);
create unique index if not exists meeting_requests_session_slot_idx
  on public.meeting_requests (session_id, coalesce(requested_for_text, ''))
  where session_id is not null;

-- ---------------------------------------------------------------------------
-- updated_at triggers
-- ---------------------------------------------------------------------------
create or replace function public.touch_updated_at() returns trigger
language plpgsql as $fn$
begin
  new.updated_at = now();
  return new;
end
$fn$;

drop trigger if exists t_bots_touch on public.bots;
create trigger t_bots_touch before update on public.bots
  for each row execute function public.touch_updated_at();

drop trigger if exists t_leads_touch on public.leads;
create trigger t_leads_touch before update on public.leads
  for each row execute function public.touch_updated_at();

drop trigger if exists t_meetings_touch on public.meeting_requests;
create trigger t_meetings_touch before update on public.meeting_requests
  for each row execute function public.touch_updated_at();

drop trigger if exists t_keys_touch on public.provider_keys;
create trigger t_keys_touch before update on public.provider_keys
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- action_items -- one feed for the Action Items dashboard page, so it can be
-- served by a single PostgREST call instead of two round trips plus a merge.
-- ---------------------------------------------------------------------------
create or replace view public.action_items as
  select
    'lead'::text                                as kind,
    l.id                                        as id,
    l.bot_id                                    as bot_id,
    b.name                                      as bot_name,
    l.session_id                                as session_id,
    coalesce(l.name, l.email, l.phone)          as who,
    l.email                                     as email,
    l.phone                                     as phone,
    l.intent                                    as what,
    l.summary                                   as summary,
    l.context_snippet                           as context_snippet,
    l.status                                    as status,
    l.created_at                                as created_at
  from public.leads l
  left join public.bots b on b.id = l.bot_id
  union all
  select
    'meeting'::text,
    m.id,
    m.bot_id,
    b.name,
    m.session_id,
    coalesce(m.name, m.email, 'Meeting request'),
    m.email,
    null,
    m.requested_for_text,
    m.topic,
    m.context_snippet,
    m.status,
    m.created_at
  from public.meeting_requests m
  left join public.bots b on b.id = m.bot_id;

-- ---------------------------------------------------------------------------
-- RLS: enabled everywhere, zero policies. Service role only.
-- ---------------------------------------------------------------------------
alter table public.bots             enable row level security;
alter table public.knowledge_docs   enable row level security;
alter table public.provider_keys    enable row level security;
alter table public.chat_sessions    enable row level security;
alter table public.chat_messages    enable row level security;
alter table public.leads            enable row level security;
alter table public.meeting_requests enable row level security;
alter table public.lead_captures    enable row level security;
